### PR TITLE
Add support for API key input

### PR DESCRIPTION
**Pull request by DarianHole**
Hi @kblin,

I've added a parameter to allow the user to provide their NCBI API key when doing requests. 

Please let me know what you think and if I should change/modify anything on this. I think that maybe I should add an error for an invalid API key input but I'm curious on your thoughts first.

edit for small note: ID not found and wrong API key are the same error number --> 400 

Darian

### CODE REVIEW

**Comment by zdk123** [comment]
FWIW, I vote for this being integrated.

**Comment by kblin** [comment]
Hi there. I apparently missed the notification for this PR in March, sorry about that.

**Comment by DarianHole** [comment]
@kblin Oh no worries on that, I probably should have asked for a review ages ago too! 

I'm a bit swamped at the moment but I could hopefully make those changes sometime for next week provided you give me what you want modified about the version number as everyone likes it done differently :)

**Comment by kblin** [comment]
Hi @DarianHole, thanks again for your contribution! Sorry this all took so long.

**Pull request merged**
